# Generated by Django 4.1.1 on 2022-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to _product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_colletion (title)
            V
        """)
    ]
